[{"ContainerToolsException.Message":"Error response from daemon: Cannot kill container: 197ea30e8c975d0b030e7a5867d446e5c28e1da79aff8841943eef2106090a9c: Container 197ea30e8c975d0b030e7a5867d446e5c28e1da79aff8841943eef2106090a9c is not running","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__32.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 424\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker-compose","ContainerToolsException.CommandLine.TelemetrySafeArguments":"","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"Container catalog.api  Killing\r\nContainer discount.api  Killing\r\nContainer discountdb  Killing\r\nContainer catalogdb  Killing\r\nContainer basket.api  Killing\r\nContainer basketdb  Killing\r\nContainer pgadmin  Killing\r\nContainer discount.api  Error while Killing\r\nContainer basketdb  Error while Killing\r\nContainer pgadmin  Error while Killing\r\nContainer catalogdb  Error while Killing\r\nContainer discountdb  Error while Killing\r\nContainer basket.api  Error while Killing\r\nContainer catalog.api  Error while Killing\r\nError response from daemon: Cannot kill container: 197ea30e8c975d0b030e7a5867d446e5c28e1da79aff8841943eef2106090a9c: Container 197ea30e8c975d0b030e7a5867d446e5c28e1da79aff8841943eef2106090a9c is not running"},{"ContainerToolsException.Message":"Visual Studio Container Tools requires Docker to be running before building, debugging or running a containerized project.  For more info, please see: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: error during connect: This error may indicate that the docker daemon is not running.: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Ddockercompose17194347003662828503%22%3Atrue%7D%7D&limit=0\": open //./pipe/docker_engine: O sistema n├úo pode encontrar o arquivo especificado.\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__32.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 424\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() na D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 82\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Users\\marly\\OneDrive\\Área de Trabalho\\Projetos .Net\\Microsservices\\docker-compose.yml\" -f \"C:\\Users\\marly\\OneDrive\\Área de Trabalho\\Projetos .Net\\Microsservices\\docker-compose.override.yml\" -p dockercompose17194347003662828503 --ansi never kill\r\nCódigo de saída do comando: 1\r\nSaída de comando: \r\nErro de comando: error during connect: This error may indicate that the docker daemon is not running.: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Ddockercompose17194347003662828503%22%3Atrue%7D%7D&limit=0\": open //./pipe/docker_engine: O sistema n├úo pode encontrar o arquivo especificado.\r\n"}]